# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "firstname": "Keks",
  "lastname": "Smith",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/67d957b2-9213-4876-bfb0-5d7e52f463be HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
